server:
    port: 3355
spring:
    profiles: dev
    application:
        name: cloud-config-client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka,http://localhost:7003/eureka
  instance:
    instance-id: config-client
---
server:
    port: 8202
spring:
    profiles: test
    application:
        name: cloud-config-client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka,http://localhost:7003/eureka
  instance:
    instance-id: config-client