spring:
    profiles:
        active:
        - dev
---
server:
    port: 7001
spring:
    profiles: dev
    application:
        name: config-eureka-client
eureka:
    instance:
        hostname: localhost #eureka服务端的实例名称
    client:
        #false表示不向注册中心注册自己
        register-with-eureka: false
        #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
        fetch-registry: false
        service-url:
            #设置与Eureka Server交互的地址查询服务和注册服务
            defaultZone: http://localhost:7001/eureka/
---
server:
    port: 7001 #注册中心占用7001端口，冒号后面必须有空格
spring:
    profiles: test
    application:
        name: config-eureka-client
eureka:
    instance:
        hostname: localhost #eureka服务端的实例名称
    client:
        #false表示不向注册中心注册自己
        register-with-eureka: false
        #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
        fetch-registry: false
        service-url:
            #设置与Eureka Server交互的地址查询服务和注册服务
            defaultZone: http://localhost:7001/eureka/
   
